apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parsons-db-backup-pvc
  namespace: timed-parsons
  labels:
    app: faded-parsons-production
    component: db-backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: thin-csi
  resources:
    requests:
      storage: 20Gi
